### ISSUE TITLE
Your WhiteNoise configuration is incompatible with WhiteNoise v4.0 This can be fixed by following the upgrade instructions at: http://whitenoise.evans.io/en/stable/changelog.html#v4-0

### ISSUE THREAD

**Issue by officerebel** [TwilioDevEd/server-notifications-django#7]
Your WhiteNoise configuration is incompatible with WhiteNoise v4.0
This can be fixed by following the upgrade instructions at:
http://whitenoise.evans.io/en/stable/changelog.html#v4-0

I added  
in common.py
MIDDLEWARE_CLASSES = (
# 'django.middleware.security.SecurityMiddleware',
    'twilio_notifications.middleware.TwilioNotificationsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',

]

But cannot get rid of the mention and run the application.

**Comment by smendes** [comment]
Hello, 
thank you very much to have raised this issue. And I apologize for the time it took for taking care of it. That project was old and `Whitenoise` version wasn't pinned, causing this problem.

Given that this tutorial isn't even using any static file, I removed `Whitenoise` and upgraded it to use the latest version of Django.

**Comment by racs93** [comment]
> Hello,
> thank you very much to have raised this issue. And I apologize for the time it took for taking care of it. That project was old and `Whitenoise` version wasn't pinned, causing this problem.
> 
> Given that this tutorial isn't even using any static file, I removed `Whitenoise` and upgraded it to use the latest version of Django.

hello, what do you mean by pinned?
